cp -f ../../../TinyGalaksijattgovga32/galaksija/*.cpp ../galaksija/
cp -f ../../../TinyGalaksijattgovga32/galaksija/*.h ../galaksija/
cp -f ../../../TinyGalaksijattgovga32/galaksija/galaksija.ino ../galaksija/
cp -f ../../../TinyGalaksijattgovga32/galaksija/dataFlash/gbgal.h ../galaksija/
cp -f ../../../TinyGalaksijattgovga32/galaksija/dataFlash/gbgtp.h ../galaksija/
cp -f ../../../TinyGalaksijattgovga32/galaksija/dataFlash/gbCompileDataOpt.h ../galaksija/
cp -f ../../../TinyGalaksijattgovga32/galaksija/dataFlash/gtp/*.h ../galaksija/
cp -f ../../../TinyGalaksijattgovga32/galaksija/dataFlash/gal/*.h ../galaksija/
cp -f notdelete/gbCompileOpt.h ../galaksija/